[package]
name = "mandel_fast"
version = "0.1.0"
edition = "2021"

[lib]
name = "mandel_fast"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
rayon = "1.10.0"
